# Generated by Django 2.1 on 2018-11-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0004_auto_20181106_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='auth',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='person',
            name='pwd',
            field=models.CharField(default='123456', max_length=256),
        ),
        migrations.AlterField(
            model_name='person',
            name='user_name',
            field=models.CharField(default='abcdef', max_length=32),
        ),
    ]
