# Generated by Django 2.1 on 2018-11-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0006_auto_20181106_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='user_name',
            field=models.CharField(default='abcdef', error_messages={'unique': 'username already been taken'}, max_length=32, unique=True),
        ),
    ]
